### ISSUE TITLE
TypeError: superclass mismatch for class Cipher

### ISSUE THREAD

**Issue by zeninfinity** [minimul/qbo_api#101]
Going through your setup instructions I get the following error:

```
Boot Error
Something went wrong while loading example/oauth2.rb

TypeError: superclass mismatch for class Cipher
/Users/z/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/openssl/cipher.rb:64:in `<class:Cipher>'
/Users/z/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/openssl/cipher.rb:16:in `<module:OpenSSL>'
/Users/z/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/openssl/cipher.rb:15:in `<top (required)>'
/Users/z/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/openssl.rb:17:in `require'
/Users/z/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/openssl.rb:17:in `<top (required)>'
/Users/z/.rvm/gems/ruby-2.4.2/gems/rack-2.0.7/lib/rack/session/cookie.rb:1:in `require'
/Users/z/.rvm/gems/ruby-2.4.2/gems/rack-2.0.7/lib/rack/session/cookie.rb:1:in `<top (required)>'
/Users/z/.rvm/gems/ruby-2.4.2/gems/sinatra-2.0.5/lib/sinatra/base.rb:1776:in `require'
/Users/z/.rvm/gems/ruby-2.4.2/gems/sinatra-2.0.5/lib/sinatra/base.rb:1776:in `<class:Base>'
/Users/z/.rvm/gems/ruby-2.4.2/gems/sinatra-2.0.5/lib/sinatra/base.rb:894:in `<module:Sinatra>'
/Users/z/.rvm/gems/ruby-2.4.2/gems/sinatra-2.0.5/lib/sinatra/base.rb:22:in `<top (required)>'
/Users/z/.rvm/gems/ruby-2.4.2/gems/sinatra-2.0.5/lib/sinatra/main.rb:1:in `require'
/Users/z/.rvm/gems/ruby-2.4.2/gems/sinatra-2.0.5/lib/sinatra/main.rb:1:in `<top (required)>'
/Users/z/.rvm/gems/ruby-2.4.2/gems/sinatra-2.0.5/lib/sinatra.rb:1:in `require'
/Users/z/.rvm/gems/ruby-2.4.2/gems/sinatra-2.0.5/lib/sinatra.rb:1:in `<top (required)>'
/Users/z/.rvm/rubies/ruby-2.4.2/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:81:in `require'
/Users/z/.rvm/rubies/ruby-2.4.2/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:81:in `block (2 levels) in require'
/Users/z/.rvm/rubies/ruby-2.4.2/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:76:in `each'
/Users/z/.rvm/rubies/ruby-2.4.2/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:76:in `block in require'
/Users/z/.rvm/rubies/ruby-2.4.2/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:65:in `each'
/Users/z/.rvm/rubies/ruby-2.4.2/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:65:in `require'
/Users/z/.rvm/rubies/ruby-2.4.2/lib/ruby/site_ruby/2.4.0/bundler/inline.rb:70:in `gemfile'
/Users/z/git/lp/qbo_api/example/oauth2.rb:6:in `<top (required)>'
/Users/z/.rvm/rubies/ruby-2.4.2/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/z/.rvm/rubies/ruby-2.4.2/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/z/.rvm/gems/ruby-2.4.2/gems/shotgun-0.9.2/lib/shotgun/loader.rb:115:in `inner_app'
/Users/z/.rvm/gems/ruby-2.4.2/gems/shotgun-0.9.2/lib/shotgun/loader.rb:103:in `assemble_app'
/Users/z/.rvm/gems/ruby-2.4.2/gems/shotgun-0.9.2/lib/shotgun/loader.rb:86:in `proceed_as_child'
/Users/z/.rvm/gems/ruby-2.4.2/gems/shotgun-0.9.2/lib/shotgun/loader.rb:31:in `call!'
/Users/z/.rvm/gems/ruby-2.4.2/gems/shotgun-0.9.2/lib/shotgun/loader.rb:18:in `call'
/Users/z/.rvm/gems/ruby-2.4.2/gems/shotgun-0.9.2/lib/shotgun/favicon.rb:12:in `call'
/Users/z/.rvm/gems/ruby-2.4.2/gems/rack-2.0.7/lib/rack/urlmap.rb:68:in `block in call'
/Users/z/.rvm/gems/ruby-2.4.2/gems/rack-2.0.7/lib/rack/urlmap.rb:53:in `each'
/Users/z/.rvm/gems/ruby-2.4.2/gems/rack-2.0.7/lib/rack/urlmap.rb:53:in `call'
/Users/z/.rvm/gems/ruby-2.4.2/gems/rack-2.0.7/lib/rack/builder.rb:153:in `call'
/Users/z/.rvm/gems/ruby-2.4.2/gems/puma-3.12.0/lib/puma/configuration.rb:225:in `call'
/Users/z/.rvm/gems/ruby-2.4.2/gems/puma-3.12.0/lib/puma/server.rb:658:in `handle_request'
/Users/z/.rvm/gems/ruby-2.4.2/gems/puma-3.12.0/lib/puma/server.rb:472:in `process_client'
/Users/z/.rvm/gems/ruby-2.4.2/gems/puma-3.12.0/lib/puma/server.rb:332:in `block in run'
/Users/z/.rvm/gems/ruby-2.4.2/gems/puma-3.12.0/lib/puma/thread_pool.rb:133:in `block in spawn_thread'
```

```
$ ruby --version
ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin18]
```

seen this before?

**Comment by zeninfinity** [comment]
Welp, upgraded to ruby-2.5.3 and got it working....

**Comment by naigueldev** [comment]
Hello, I installed bundler 1.17.3 with `gem install bundler -v '1.17.3'`, run the `bundle install`, run `rails server` and it worked.
